/* =============================================================
   NOVEM CONTROLS — NOTIFICATIONS PAGE
   Renders real notifications generated by actual actions taken
   in the portal (members added/removed, broadcasts sent, MFA
   changes, etc.) — see js/dashboard.js's Novem.addNotification().
   ========================================================= */

(function () {
    "use strict";

    const N = window.Novem;

    const listEl = document.getElementById("notificationList");
    const emptyState = document.getElementById("emptyNotifications");
    const tabs = Array.from(document.querySelectorAll(".notification-tab"));

    let activeFilter = "all";

    const ICONS = {
        security: "bi-shield-exclamation",
        system: "bi-cpu-fill",
        member: "bi-person-plus",
        message: "bi-chat-left-text-fill"
    };

    function escapeHtml(str) {
        return String(str).replace(/[&<>"']/g, function (c) {
            return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
        });
    }

    function timeAgo(iso) {
        const diffMs = Date.now() - new Date(iso).getTime();
        const mins = Math.floor(diffMs / 60000);
        if (mins < 1) return "just now";
        if (mins < 60) return mins + " minute" + (mins === 1 ? "" : "s") + " ago";
        const hours = Math.floor(mins / 60);
        if (hours < 24) return hours + " hour" + (hours === 1 ? "" : "s") + " ago";
        const days = Math.floor(hours / 24);
        return days + " day" + (days === 1 ? "" : "s") + " ago";
    }

    /* =========================================================
       RENDER
       ========================================================= */

    function render() {
        const all = N.getNotifications();

        // Summary counts (always reflect the FULL set, not the filtered view)
        document.getElementById("unreadCount").textContent = all.filter(function (n) { return n.unread; }).length;
        document.getElementById("securityCount").textContent = all.filter(function (n) { return n.unread && n.type === "security"; }).length;
        document.getElementById("systemCount").textContent = all.filter(function (n) { return n.unread && n.type === "system"; }).length;
        document.getElementById("messageCount").textContent = all.filter(function (n) { return n.unread && n.type === "message"; }).length;

        N.syncNotificationBadge();

        const visible = all.filter(function (n) {
            if (activeFilter === "all") return true;
            if (activeFilter === "unread") return n.unread;
            return n.type === activeFilter;
        });

        if (visible.length === 0) {
            listEl.innerHTML = "";
            emptyState.classList.add("show");

            const heading = emptyState.querySelector("h4");
            const body = emptyState.querySelector("p");
            if (all.length === 0) {
                heading.textContent = "No notifications yet";
                body.textContent = "Activity like new members, broadcasts and security changes will show up here.";
            } else {
                heading.textContent = "No notifications found";
                body.textContent = "There are no notifications matching this filter.";
            }
            return;
        }

        emptyState.classList.remove("show");

        listEl.innerHTML = visible.map(function (n) {
            const priorityTag = n.priority === "high"
                ? '<span class="priority high">High Priority</span>'
                : "";

            const markReadBtn = n.unread
                ? '<button class="notification-action mark-read" data-id="' + n.id + '" title="Mark as read"><i class="bi bi-check2"></i></button>'
                : '<button class="notification-action" title="Notification read"><i class="bi bi-check2"></i></button>';

            return '<div class="notification-item ' + (n.unread ? "unread" : "") + '" data-type="' + n.type + '">' +
                '<div class="notification-icon ' + n.type + '"><i class="bi ' + (ICONS[n.type] || "bi-bell") + '"></i></div>' +
                '<div class="notification-content">' +
                '<div class="notification-title-row"><h4>' + escapeHtml(n.title) + "</h4>" + priorityTag + "</div>" +
                "<p>" + escapeHtml(n.message) + "</p>" +
                '<span class="notification-time"><i class="bi bi-clock"></i> ' + timeAgo(n.time) + "</span>" +
                "</div>" +
                markReadBtn +
                "</div>";
        }).join("");
    }

    /* =========================================================
       ACTIONS
       ========================================================= */

    listEl.addEventListener("click", function (e) {
        const btn = e.target.closest(".notification-action.mark-read");
        if (!btn) return;

        const id = btn.getAttribute("data-id");
        const all = N.getNotifications();
        const item = all.find(function (n) { return n.id === id; });
        if (item) item.unread = false;
        N.write("novem_notifications", all);
        render();
    });

    tabs.forEach(function (tab) {
        tab.addEventListener("click", function () {
            tabs.forEach(function (t) { t.classList.remove("active"); });
            tab.classList.add("active");
            activeFilter = tab.getAttribute("data-filter");
            render();
        });
    });

    document.getElementById("markAllRead").addEventListener("click", function () {
        const all = N.getNotifications();
        all.forEach(function (n) { n.unread = false; });
        N.write("novem_notifications", all);
        render();
        N.toast("All notifications marked as read.", "success");
    });

    document.getElementById("refreshNotifications").addEventListener("click", function () {
        render();
        N.toast("Notifications refreshed.", "info");
    });

    /* =========================================================
       INIT
       ========================================================= */

    render();

})();
